spring:
  datasource:
    url: jdbc:h2:file:./data/codearena;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE;MODE=MySQL
    username: sa
    password: ${H2_PASSWORD:password}
    driver-class-name: org.h2.Driver

  h2:
    console:
      enabled: true
      path: /h2-console

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.H2Dialect
        format_sql: true
    defer-datasource-initialization: true

logging:
  level:
    root: INFO
    "[com.codearena]": DEBUG
    "[org.springframework.security]": INFO
    "[org.hibernate.SQL]": DEBUG
    "[org.hibernate.type.descriptor.sql.BasicBinder]": TRACE

server:
  error:
    include-message: always
    include-binding-errors: always
    include-stacktrace: on_param
